---
- name: Despliegue MEC
  hosts: PRUEBA
  tasks:
    - name: Detener pool PoolApiMec
      community.windows.win_iis_webapppool:
        name: PoolApiMec
        state: stopped
    
    - name: Detener pool PoolMec
      community.windows.win_iis_webapppool:
        name: PoolMec
        state: stopped
    
    - name: copiar carpeta ApiMec
       win_copy:
         src: /opt/windows/despliegue_MEC_Agosto8_2024/ACTIVIDADES/ApiMEC/
         dest: E:\Pruebas\ApiMec
         force: yes
         
    - name: copiar carpeta 
       win_copy:
         src: /opt/windows/despliegue_MEC_Agosto8_2024/ACTIVIDADES/MEC/
         dest: E:\Pruebas\Mec
         force: yes
    
    - name: Arrancar pool PoolMec
      community.windows.win_iis_webapppool:
        name: PoolMec
        state: started

    - name: Arrancar pool PoolApiMec
      community.windows.win_iis_webapppool:
        name: PoolApiMec
        state: started
