---
- name: robocopy
  hosts: maquina
  tasks:
   - name: sincronizar archivos
     community.windows.win_robocopy:
       src: "D:\\wbsnet"
       dest: "P:\\CGC\\PROYECTOS - CONTRATOS\\Contratos\\Vigentes\\ENLACE OPERATIVO\\Modelo de Operativo\\Copia\\"
       purge: false
       flags: /S
