---
- name: Arrancar un servicio
  hosts: maquina
  tasks:
  - name: Detener servicio
    ansible.windows.win_service:
      name: Audiosrv
      state: stopped

  - name: Arrancar servicio
    ansible.windows.win_service:
      name: Audiosrv
      state: started
